# name: Azure Infrastructure Setup

# on:
#   push:
#     branches:
#       - dev 

# permissions:
#   id-token: write
#   contents: read

# env:
#   TF_VAR_azure_region: 'australiaeast'
#   TF_VAR_resource_group_name: 'microservices-demo-rg'
#   TF_VAR_acr_name: 'shaheergooglepracticeregistry'

# jobs:
#   setup_infrastructure:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Install Azure CLI
#       run: |
#         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

#     - name: Azure login
#       uses: azure/login@v1.4.7
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: Install Terraform
#       run: |
#         sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
#         curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
#         sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
#         sudo apt-get update && sudo apt-get install terraform

#     - name: Check if Terraform directory exists
#       run: |
#         if [ ! -d "deployment/terraform/aks" ]; then
#           echo "Directory deployment/terraform/aks does not exist."
#           exit 1
#         fi

#     - name: Initialize Terraform
#       run: |
#         cd deployment/terraform/aks
#         terraform init

#     - name: Import Existing Resource Group
#       run: |
#         terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/microservices-demo-rg || true
#       working-directory: deployment/terraform/aks

#     - name: Apply Terraform Configuration
#       run: |
#         cd deployment/terraform/aks
#         terraform apply -auto-approve
